### ISSUE TITLE
how to register registerMessageListener

### ISSUE THREAD

**Issue by lyxaaadf** [apache/rocketmq-spring#111]
alibaba give translation demo :
consumer.registerMessageListener(new MessageListenerConcurrently() {

            @Override
            public ConsumeConcurrentlyStatus consumeMessage(List<MessageExt> msgs,
                ConsumeConcurrentlyContext context) {
            	for(MessageExt msg:msgs){
            		try {
						System.out.println("消息内容为1："+new String(msg.getBody(),RemotingHelper.DEFAULT_CHARSET));
					} catch (UnsupportedEncodingException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
            	}
                return ConsumeConcurrentlyStatus.CONSUME_SUCCESS;
            }
        });

but our's ,i cant find this ,so What should I do?
our's  demo：

@Service
@RocketMQMessageListener(topic = "tro",consumerGroup ="evaluation-trans")
public class MyTransactionConsumer implements RocketMQListener<String>{

	@Override
	public void onMessage(String message) {
		System.out.println("consumer:....."+message);
		
	}
	
	

}
tell me .pls

**Comment by lyxaaadf** [comment]
yes,when consum fail ,i can renturn :ConsumeConcurrentlyStatus.CONSUME_SUCCESS; but demo is void

**Comment by RongtongJin** [comment]
@lyxaaadf If no RuntimeException is thrown in onMessage method, it will return ConsumeConcurrentlyStatus.CONSUME_SUCCESS by default. Otherwise, return ConsumeConcurrentlyStatus.RECONSUME_LATER. 
https://github.com/apache/rocketmq-spring/blob/cc1a340d980703a1c810b99fd361b8fb70cbc97d/rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java#L321-L342
