### ISSUE TITLE
Add some asynchronous API for batch messages in RocketMQTemplate.

### ISSUE THREAD

**Issue by zhangjidi2016** [apache/rocketmq-spring#371]
**Enhancement**

Add some asynchronous API for batch messages in RocketMQTemplate.

**Comment by zongtanghu** [comment]
The related pr has already been merged, so I closed this issues!

**Comment by vongosling** [comment]
@zongtanghu you could not close pr by yourself. just link the pr with the issue. when merging to the main branch, it will automatically close.

**Comment by zongtanghu** [comment]
ok!


 原始邮件 
发件人: von ***@***.***>
收件人: ***@***.***>
抄送: Hu ***@***.***>; ***@***.***>
发送时间: 2021年8月12日(周四) 09:30
主题: Re: [apache/rocketmq-spring] Add some asynchronous API for batchmessages in RocketMQTemplate. (#371)


@zongtanghu you could not close pr by yourself. just link the pr with the issue. when merging to the main branch, it will automatically close.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
