### ISSUE TITLE
Exclude annotations-api to make spring-boot start normally

### ISSUE THREAD

**Issue by RongtongJin** [apache/rocketmq-spring#629]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

Exclude annotations-api to make spring-boot start normally

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `type/bug` | Status: **Confirmed**

`annotations-api` dependency conflict causing Spring Boot startup failure is a valid bug. The `annotations-api` JAR can conflict with servlet API classes provided by the container, causing classloading issues.

**Root Cause:** Transitive dependency on `annotations-api` that conflicts with the servlet container's provided classes.
**Impact:** Spring Boot application fails to start — blocks usage entirely.
**Severity:** High — prevents application startup.

**Suggested fix:** Exclude `annotations-api` from the dependency tree via `<exclusions>` in the relevant `pom.xml`.

---
*Automated evaluation by github-manager*
