### ISSUE TITLE
The code for version 2.3.0 seems to be fine now. Could you package it when you have time and upload it to the Maven Central Repository?

### ISSUE THREAD

**Issue by OPGithub** [apache/rocketmq-spring#635]
2.3.0的版本看代码看起来已经好了，有空打包一个，放到maven的中央仓库么

The code for version 2.3.0 seems to be fine now. Could you package it when you have time and upload it to the Maven Central Repository?

**Comment by XJhrack** [comment]
+1

**Comment by newbitwhite** [comment]
+1

**Comment by RongtongJin** [comment]
done

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `question` | Status: **Evaluated (Release request)**

This is a request to package and release version 2.3.0 to Maven Central.

**Note:** Release coordination is a maintainer responsibility. Please check the project's release schedule or contact the maintainers through the [mailing list](http://rocketmq.apache.org/about/contact/).

**Age:** This issue is from February 2024.

---
*Automated evaluation by RockteMQ-AI*
