### ISSUE TITLE
Upgrade samples version to 2.3.1-SNAPSHOT

### ISSUE THREAD

**Issue by RongtongJin** [apache/rocketmq-spring#637]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

Upgrade samples version to 2.3.1-SNAPSHOT

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `enhancement` | Status: **Evaluated (Maintenance)**

This is a version upgrade task to bump samples to 2.3.1-SNAPSHOT.

**Note:** This is a maintenance/chore task that requires maintainer action. It's not a code bug or feature request.

**Age:** This issue is from March 2024. If this upgrade is still needed, a maintainer should address it.

---
*Automated evaluation by RockteMQ-AI*
