### ISSUE TITLE
Add simple demo for samples

### ISSUE THREAD

**Issue by drpmma** [apache/rocketmq-spring#660]
The original samples were too lengthy and complicated, making them difficult to understand, so a much simpler demo has been added.

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `enhancement` | Status: **Evaluated**

**Feasibility:** Feasible
**Scope:** Samples/documentation module

Adding a simpler demo for the RocketMQ Spring samples is a good idea. The existing samples can be overwhelming for newcomers. A minimal working example (e.g., a simple producer/consumer with basic configuration) would lower the barrier to entry.

Recommend:
- Create a `rocketmq-spring-boot-sample-simple` module or add a simplified example to the existing sample
- Include only essential configuration (nameserver address, topic, group)
- Add clear README with step-by-step instructions

This issue is from 2024 and appears to still be relevant. A PR with a simplified demo would be welcome.

---
*Automated evaluation by RockteMQ-AI*
