### ISSUE TITLE
Ugly code

### ISSUE THREAD

**Issue by x-wk** [apache/rocketmq-spring#667]
```java

      try {
         Message<?> message = MessageBuilder.withPayload(payloadBuilder.build())
            .setHeader(RocketMQHeaders.KEYS, keys)
            .build();

         // send
         SendReceipt sendReceipt = rocketMQClientTemplate.syncSendNormalMessage(MQTopics.XXX_TOPIC, message);

         // no exception?
         if (sendReceipt == null) {
            throw new RuntimeError("1111", "Failure");
         }
      } catch (Exception e) {
         throw new RuntimeError("1111", "Failure");
      }

```
Ugly...🤮

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `question` | Status: **Needs Info**

Thank you for raising this. The code snippet shows a pattern where `syncSendNormalMessage` returns a null `SendReceipt` and the error handling wraps everything in a generic catch block.

To provide actionable feedback, could you clarify what specific improvement you are looking for?

- [ ] Is the null check on `SendReceipt` unnecessary? (Does the API guarantee non-null or throw on failure?)
- [ ] Is the try-catch pattern too broad? (Should it catch specific exceptions?)
- [ ] Is there a preferred API pattern for synchronous sends in rocketmq-spring?

Providing more context about the expected behavior and the specific concern will help the community address this effectively.

---
*Automated evaluation by RockteMQ-AI*
