### ISSUE TITLE
Why RocketMQ Spring Boot Starter V2.2.3 use RocketMQ client 5.0?Why not 4.9.x?

### ISSUE THREAD

**Issue by zhangdp** [apache/rocketmq-spring#680]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `question` | Status: **Answered**

RocketMQ Spring Boot Starter 2.2.3 uses RocketMQ client 5.x because the 2.2.x release line targets compatibility with the RocketMQ 5.x ecosystem, which introduced significant improvements including:

- **gRPC-based protocol** (replacing the legacy Remoting protocol for client-proxy communication)
- **Improved message model** with better transaction and delay message support
- **Unified client architecture** across languages (Java/Go/C++/C#/Rust)

The 4.9.x client line uses the older Remoting protocol and is maintained separately. If your deployment uses RocketMQ 4.x servers, you should use a Starter version from the 2.1.x line (e.g., 2.1.5) which bundles the 4.9.x client.

**Version mapping:**
| Starter Version | Client Version | Server Compatibility |
|----------------|---------------|---------------------|
| 2.1.x | 4.9.x | RocketMQ 4.x |
| 2.2.x | 5.x | RocketMQ 5.x (also supports 4.x in compatibility mode) |

For migration guidance, refer to the [RocketMQ 5.0 upgrade documentation](https://rocketmq.apache.org/docs/deploymentOperations/01QuickStart/).

---
*Automated evaluation by github-manager*
